name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update APT and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            extra-cmake-modules \
            qt6-base-dev \
            qt6-declarative-dev \
            libkf6kirigami-dev \
            libkf6globalaccel-dev

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build KAI
        run: cmake --build build --parallel $(nproc)
